track_names = [ 
  "(Anesthesia) Pulling Teeth",
"(Da Le) Yaleo",
"(I Can't Help) Falling In Love With You",
"(Oh) Pretty Woman",
"(There Is) No Greater Love (Teo Licks)",
"(We Are) The Road Crew",
"(White Man) In Hammersmith Palais",
"(Wish I Could) Hideaway",
"...And Found",
"...And Justice For All",
"...In Translation",
".07%",
"01 - Prowler",
"02 - Sanctuary",
"03 - Remember Tomorrow",
"04 - Running Free",
"05 - Phantom of the Opera",
"06 - Transylvania",
"07 - Strange World",
"08 - Charlotte the Harlot",
"09 - Iron Maiden",
"1/2 Full",
"100% HardCore",
"13 Years Of Grief",
"14 Years",
"16 Toneladas",
"1979",
"19th Nervous Breakdown",
"1° De Julho",
"1º De Julho",
"2 A.M.",
"2 Minutes To Midnight",
"2 Minutes To Midnight",
"2 Minutes To Midnight",
"2 Minutes To Midnight",
"2 Minutes To Midnight",
"2 X 4",
"2,000 Man",
"20 Flight Rock",
"200 Years Old",
"2112 Overture",
"22 Acacia Avenue",
"24 Caprices, Op. 1, No. 24, for Solo Violin, in A Minor",
"3 Gymnopédies: No.1 - Lent Et Grave, No.3 - Lent Et Douloureux",
"32 Dentes",
"5.15",
"51st Anniversary",
"A Banda",
"A Bencao E Outros",
"A Benihana Christmas, Pts. 1 & 2",
"A Carta",
"A Castle Full Of Rascals",
"A Cor Do Sol",
"A Cor Do Sol",
"A Cura",
"A Day In the Life",
"A Different Kind Of Blue",
"A E O Z",
"A Estrada",
"A Estrada",
"A Festa Do Santo Reis",
"A Kind Of Magic",
"A Luz De Tieta",
"A Man And A Woman",
"A Measure of Salvation",
"A Melhor Forma",
"A Menina Dança",
"A Midsummer Night's Dream, Op.61 Incidental Music: No.7 Notturno",
"A Moça e a Chuva",
"A New Flame",
"A Noite Do Meu Bem",
"A Novidade",
"A Novidade (Live)",
"A Paz",
"A Paz",
"A Room At The Heartbreak Hotel",
"A Rua",
"A Small Victory",
"A Sombra Da Maldade",
"A Sombra Da Maldade",
"A Statistic",
"A Sua",
"A Tale of Two Cities",
"A Tarde",
"A Touch Away",
"A Twist In The Tail",
"A Via Láctea",
"A Volta Da Asa Branca",
"A World Without Heroes",
"A Última Guerra",
"A.N.D.R.O.T.A.Z.",
"Abandoned",
"Abraham, Martin And John",
"Abrir A Porta",
"Absolute Zero",
"Acacia Avenue",
"Ace Of Spades",
"Acelerou",
"Acelerou",
"Aces High",
"Aces High",
"Achilles Last Stand",
"Acrobat",
"Act IV, Symphony",
"Action",
"Adagio for Strings from the String Quartet, Op. 11",
"Adeus",
"Adios nonino",
"Admirável Gado Novo",
"Adoled (Ocean)",
"Adrift",
"Advance Romance",
"Aeroplane Flies High",
"Afraid",
"Afraid To Shoot Strangers",
"Afraid To Shoot Strangers",
"Afraid To Shoot Strangers",
"Africa Bamba",
"After Midnight",
"Aftermath",
"Again",
"Age Of Innocence",
"Agora Que O Dia Acordou",
"Aguia De Ouro 2001",
"Ain't My Bitch",
"Ain't Talkin' 'Bout Love",
"Ain't Talkin' 'bout Love",
"Ainda Lembro",
"Ainda É Cedo",
"Alabama Song",
"Alagados",
"Alarum",
"Alberta",
"Alcohol",
"Alegria, Alegria",
"Alexander the Great",
"Ali",
"Alice",
"Alive",
"All Along The Watchtower",
"All Because Of You",
"All Dead, All Dead",
"All For You",
"All I Really Want",
"All I Want Is You",
"All I Want Is You",
"All My Life",
"All My Love",
"All My Love",
"All Night Thing",
"All Star",
"All Within My Hands",
"All or None",
"All the Best Cowboys Have Daddy Issues",
"Aloha",
"Always Be All Right",
"Always Forever Now",
"Always On The Run",
"Always With Me, Always With You",
"Alô Alô Marciano",
"Alô, Alô, Marciano",
"Am I Evil?",
"Amanda",
"Amanhã Não Se Sabe",
"Amar É Tudo",
"Amazing",
"American Gothic",
"American Idiot",
"American Woman",
"Amor De Muito",
"Amor Demais",
"Amy Amy Amy (Outro)",
"And the Cradle Will Rock...",
"Ando Meio Desligado",
"Ando Meio Desligado",
"Aneurysm",
"Angel",
"Angel",
"Angel Of Harlem",
"Angel Of Harlem",
"Angela",
"Animal",
"Animal",
"Another Life",
"Another One Bites The Dust",
"Another Round",
"Antene Se",
"Antes Das Seis",
"Anthem",
"Any Colour You Like",
"Anya",
"Anyone's Daughter",
"Anything Goes",
"Anyway, Anyhow, Anywhere",
"Ao Meu Redor",
"Aonde Quer Que Eu Va",
"Aos Leões",
"Apache Rose Peacock",
"Apesar De Você",
"Aprendendo A Jogar",
"Aquarela (Toquinho)",
"Aquele Abraço",
"Aquilo",
"Arc",
"Are We The Waiting",
"Are You Experienced?",
"Are You Gonna Be My Girl",
"Are You Gonna Go My Way",
"Aria Mit 30 Veränderungen, BWV 988 ""Goldberg Variations"": Aria",
"Armadura",
"Armageddon It",
"Arms Around Your Love",
"Army Ants",
"Army Reserve",
"Around The World",
"Arrepio",
"As Aparências Enganam",
"As Dores do Mundo",
"As Pegadas Do Amor",
"As Profecias",
"As Rosas Não Falam (Beth Carvalho)",
"As Tears Go By",
"As The Years Go by",
"As We Sleep",
"Asa Branca",
"Asas",
"Ashes And Ghosts",
"Ashes To Ashes",
"Assaltaram A Gramática",
"Assim Caminha A Humanidade",
"Assum Preto",
"Astronomy",
"Atomic Punk",
"Atras Da Porta",
"Atrás Da Verd-E-Rosa Só Não Vai Quem Já Morreu",
"Atrás Do Trio Elétrico",
"Atrás da Porta",
"Attitude",
"Até Que Enfim Encontrei Você",
"Ava Adore",
"Ave Maria",
"Avisa",
"Aviso Aos Navegantes",
"Azul",
"Azul Da Cor Do Mar",
"Açai",
"B.Y.O.B.",
"Baba O'Riley",
"Babe I'm Gonna Leave You",
"Baby",
"Baby Break It Down",
"Babyface",
"Babylon",
"Babylon",
"Back Door Man",
"Back from Vacation",
"Back in the Village",
"Back off Bitch",
"Back to Black",
"Bad",
"Bad Apples",
"Bad Attitude",
"Bad Boy",
"Bad Boy Boogie",
"Bad Moon Rising",
"Bad Obsession",
"Bad Seed",
"Bad, Bad Leroy Brown",
"Badge",
"Baixo Rio",
"Baião Ambiental [Instrumental]",
"Baião Da Penha",
"Balada Da Paula",
"Balada Do Amor Inabalável",
"Balada Do Louco",
"Balanço",
"Ballot or the Bullet",
"Balls to the Wall",
"Baltar's Escape",
"Baltimore, DC",
"Band Members Discuss Tracks from ""Revelations""",
"Banditismo Por Uma Questa",
"Banditismo Por Uma Questa",
"Banho De Lua",
"Bankrobber",
"Bark at the Moon",
"Basket Case",
"Basketball",
"Bass Trap",
"Bastille Day",
"Bat Macumba",
"Batalha Naval",
"Bate Lata",
"Battery",
"Battlestar Galactica, Pt. 1",
"Battlestar Galactica, Pt. 2",
"Battlestar Galactica, Pt. 3",
"Battlestar Galactica: The Story So Far",
"Be Aggressive",
"Be Good Johnny",
"Be Mine",
"Be Quick Or Be Dead",
"Be Quick Or Be Dead",
"Be Quick Or Be Dead",
"Be Yourself",
"Beach Games",
"Beach Sequence",
"Beautiful Boy",
"Beautiful Day",
"Because You Are",
"Been A Son",
"Before You Accuse Me",
"Before You Accuse Me",
"Behind The Wall Of Sleep",
"Beija Eu",
"Beija-Flor",
"Beijo Partido",
"Beijo do Olhar",
"Beira Mar",
"Believe",
"Believe",
"Believe",
"Believe in Love",
"Believer",
"Bell Bottom Blues",
"Belong",
"Bem Devagar",
"Bem Leve",
"Ben Franklin",
"Berimbau",
"Berlim",
"Best Of You",
"Best Thing",
"Beth",
"Beth",
"Better Halves",
"Better Man",
"Better Than You",
"Bichos Escrotos (Vinheta)",
"Bicycle Race",
"Big Bad Bill (Is Sweet William Now)",
"Big City Nights",
"Big Machine",
"Big Wave",
"Billie Jean",
"Binky The Doormat",
"Biruta",
"Bite The Bullet",
"Bitter Pill",
"Bitter Suite: Brief Encounter / Lost Weekend / Blue Angel",
"Bittersweet Me",
"Black",
"Black",
"Black Capricorn Day",
"Black Country Woman",
"Black Diamond",
"Black Dog",
"Black Dog",
"Black Hole Sun",
"Black Light Syndrome",
"Black Moon Creeping",
"Black Mountain Side",
"Black Night",
"Black Sabbath",
"Black Sabbath",
"Black Satin",
"Black Velveteen",
"Blackened",
"Blanco",
"Bleed The Freak",
"Bleed Together",
"Bleeding Me"
]
